<!-- Copyright © 2026 Neil Colvin.
     Licensed under the MIT License. See LICENSE file in the project root for full license information. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" PrivateAssets="all" />
    <PackageReference Include="NUnit" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
    <PackageReference Include="NUnit.Analyzers" Version="4.15.0" PrivateAssets="all" />
    <ProjectReference Include="../../src/RainPointClient.Desktop/RainPointClient.Desktop.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Net.Http" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <PropertyGroup>
    <WarningsAsErrors>$(WarningsAsErrors);CS4014</WarningsAsErrors>
  </PropertyGroup>
</Project>